services:
  - type: web
    name: barborja-app
    runtime: node
    plan: free
    branch: main
    buildCommand: npm run build
    startCommand: node ./server.mjs
    envVars:
      - key: NODE_ENV
        value: production

